# Metadata for the Smart-Plugin
plugin:
  # Global plugin attributes
  type: gateway                 # plugin type (gateway, interface, protocol, system, web)
  description:                  # Alternative: description in multiple languages
      de: 'Anbindung von Sonos Lautsprechern'
      en: 'Sonos plugin'
  maintainer: pfischi
  tester: pfischi
  state: ready
  keywords: Sonos sonos multimedia
  documentation: https://github.com/smarthomeNG/plugins/blob/master/sonos/README.md
  support: https://knx-user-forum.de/forum/supportforen/smarthome-py/25151-sonos-anbindung

  version: 1.6.9                 # Plugin version
  sh_minversion: 1.5.1           # minimum shNG version to use this plugin
  py_minversion: 3.8             # minimum Python version to use for this plugin
  multi_instance: False          # plugin supports multi instance
  restartable: unknown
  classname: Sonos               # class containing the plugin

parameters:
  tts:
    type: bool
    default: False
    description:
      de: "(optional) Aktiviert die Google TTS Funktionalität."
      en: "(optional) Enables the Google TTS functionality"

  local_webservice_path:
    type: str
    description:
      de: "(optional) In dieses Verzeichnis werden alle TTS-Dateien automatisch gespeichert. Is die Option 'tts' aktiviert, dann muss diese Option gesetzt sein."
      en: "(optional) All tts files will be stored here automatically. If 'tts' is enabled, this option is mandatory."

  local_webservice_path_snippet:
    type: str
    description:
      de: "(optional) Die eigenen Audio-Snippet Dateien können beim Setzen dieser Option getrennt von den autmotisch generierten TTS-Dateien gespeichert werden. Wird diese Option nicht gesetzt und 'tts' ist aktiviert, so wird der Wert von 'local_webservice_path' für Snippets benutzt."
      en: "(optional) The sniipet audio files can be stored separatly from the TTS audio files by activating this option. If 'tts' is enabled and this option is not set, the value 'local_webservice_path' is used for the audio snippet path."

  webservice_ip:
    type: ip
    description:
      de: "(optional) Für TTS und die Audio-Snippet-Funktionalität wird ein simpler Webservice gestartet. Die IP-Adresse wird per default automatisch ermittelt, kann hier aber manuell gesetzt werden."
      en: "(optional) For the TTS and audio snippet functionality, a simple webservice is started. By default the IP is detected automatically and can be manually overridden here."

  webservice_port:
    type: int
    default: 23500
    description:
      de: "(optional) Webservice-Port"
      en: "(optional) Webservice port"

  speaker_ips:
    type: list
    description:
      de: "(optional) Die IPs der Lautsprecher können manuell gesetzt werden. Dies kann in einer Container-Umgebung (z.B Docker) mit eingeschränkten Netzwerkzugriff sinnvoll sein."
      en: "(optional) You can set static IP addresses for your Sonos speaker. This will disable auto-discovery. This is useful if you're using a containerized environment with restricted network access."

  discover_cycle:
    type: int
    default: 180
    valid_min: 120
    description:
      de: "Zeitintervall, nach dem (erneut) nach (neuen) Lautsprechern im Netzwerk gesucht wird."
      en: "Time interval to search again for (new) speakers in the network."

  snippet_duration_offset:
    type: num
    default: 0
    valid_min: 0
    description:
      de: "(optional) Verlängert die Dauer von Snippet Audio Dateien um einen festen Offset in Sekunden."
      en: "(optional) Extend snippet duration by a fixed offset specified in seconds"

    webif_pagelength:
        type: int
        default: 0
        valid_list:
            - -1
            - 0
            - 25
            - 50
            - 100
        description:
            de: 'Anzahl an Items, die standardmäßig in einer Web Interface Tabelle pro Seite angezeigt werden.
                 0 = automatisch, -1 = alle'
            en: 'Amount of items being listed in a web interface table per page by default.
                 0 = automatic, -1 = all'
        description_long:
            de: 'Anzahl an Items, die standardmäßig in einer Web Interface Tabelle pro Seite angezeigt werden.\n
                 Bei 0 wird die Tabelle automatisch an die Höhe des Browserfensters angepasst.\n
                 Bei -1 werden alle Tabelleneinträge auf einer Seite angezeigt.'
            en: 'Amount of items being listed in a web interface table per page by default.\n
                 0 adjusts the table height automatically based on the height of the browser windows.\n
                 -1 shows all table entries on one page.'

item_attributes:
  # Definition of item attributes defined by this plugin
  sonos_uid:
    type: str
    description:
      de: 'Sonos unique device ID'
      en: 'Sonos unique device ID'
    mandatory: False

  sonos_recv:
    type: str
    description:
      de: 'Empfangsattribut'
      en: 'Receive attribute'
    mandatory: False
    valid_list:
    - is_initialized
    - volume
    - play
    - is_coordiantor
    - mute
    - stop
    - seek
    - pause
    - track_title
    - track_artist
    - track_uri
    - track_album
    - track_album_art
    - bass
    - treble
    - loudness
    - play_mode
    - radio_show
    - radio_station
    - serial_number
    - software_version
    - hardware_version
    - model
    - uid
    - ip
    - mac_address
    - status
    - additional_zone_members
    - alarms
    - is_coordinator
    - tts_local_mode
    - night_mode
    - dialog_mode
    - buttons_enabled
    - cross_fade
    - coordinator
    - snooze
    - status_light
    - zone_group_members
    - player_name
    - household_id
    - streamtype
    - current_track
    - number_of_tracks
    - current_transport_actions
    - current_valid_play_modes
    - sonos_playlists
    - stream_content
    - current_track_duration

  sonos_send:
    type: str
    description:
      de: 'Sendeattribut'
      en: 'Sending attribute'
    mandatory: 'False'
    valid_list:
    - volume
    - play
    - pause
    - stop
    - mute
    - cross_fade
    - snooze
    - play_mode
    - next
    - previous
    - play_tunein
    - play_url
    - play_sharelink
    - load_sonos_playlist
    - play_snippet
    - play_tts
    - join
    - unjoin
    - volume_up
    - volume_down
    - partymode
    - bass
    - treble
    - loudness
    - playmode
    - seek
    - status
    - alarms
    - get_playlist
    - set_playlist
    - night_mode
    - dialog_mode
    - buttons_enabled
    - cross_fade
    - snooze
    - status_light
    - switch_linein
    - switch_tv

  sonos_attrib:
    type: str
    description:
      de: 'Sonos Attribute'
      en: 'Sonos attribute'
    mandatory: 'False'
    valid_list:
    - group
    - dpt3_helper
    - vol_dpt3
    - max_volume
    - tts_language
    - tts_volume
    - tts_fade_in
    - start_after
    - snippet_fade_in
    - snippet_volume
    - clear_queue
    - start_track

  sonos_dpt3_step:
    type: int
    description:
      de: 'Relatives dpt3 Inkrement'
      en: 'Relative dpt3 increment'
    mandatory: 'False'

  sonos_dpt3_time:
    type: int
    description:
      de: 'Dpt3 Zeitinkrement'
      en: 'Dpt3 time increment'
    mandatory: 'False'

item_structs:
  basic_control:
    volume:
      type: num
      sonos_recv: volume
      sonos_send: volume
      enforce_updates: true

      group_command:
        type: bool
        value: false
        sonos_attrib: group

      max_volume:
        type: num
        value: -1
        sonos_attrib: max_volume

      volume_dpt3:
        type: list
        sonos_attrib: vol_dpt3
        sonos_dpt3_step: 2
        sonos_dpt3_time: 1

        helper:
          sonos_attrib: dpt3_helper
          type: num
          sonos_send: volume

    play:
      type: bool
      sonos_recv: play
      sonos_send: play

    stop:
      type: bool
      sonos_recv: stop
      sonos_send: stop

    pause:
      type: bool
      sonos_recv: pause
      sonos_send: pause

    next:
      type: bool
      sonos_send: next
      enforce_updates: true

    previous:
      type: bool
      sonos_send: previous
      enforce_updates: true

    mute:
      type: bool
      sonos_recv: mute
      sonos_send: mute

    play_mode:
      type: str
      sonos_recv: play_mode
      sonos_send: play_mode

  settings:
    bass:
      type: num
      sonos_recv: bass
      sonos_send: bass

      group_command:
        type: bool
        value: false
        sonos_attrib: group

    treble:
      type: num
      sonos_recv: treble
      sonos_send: treble

      group_command:
        type: bool
        value: false
        sonos_attrib: group

    loudness:
      type: bool
      sonos_recv: loudness
      sonos_send: loudness

      group_command:
        type: bool
        value: false
        sonos_attrib: group

    cross_fade:
      type: bool
      sonos_recv: cross_fade
      sonos_send: cross_fade

    snooze:
      type: num
      sonos_recv: snooze
      sonos_send: snooze

    status_light:
      type: bool
      sonos_recv: status_light
      sonos_send: status_light

    join:
      type: str
      sonos_send: join
      enforce_updates: True

    unjoin:
      type: bool
      sonos_send: unjoin
      enforce_updates: True

  status:
      uid:
        type: str
        sonos_recv: uid

      is_initialized:
        type: bool
        sonos_recv: is_initialized

      is_coordinator:
        type: bool
        sonos_recv: is_coordinator

      coordinator:
        type: str
        sonos_recv: coordinator

      zone_group_members:
        type: list
        sonos_recv: zone_group_members

      player_name:
        type: str
        sonos_recv: player_name

      household_id:
        type: str
        sonos_recv: household_id

  content:
    track_uri:
      type: str
      sonos_recv: track_uri

    streamtype:
      type: str
      sonos_recv: streamtype

    track_artist:
      type: str
      sonos_recv: track_artist

    track_title:
      type: str
      sonos_recv: track_title

    track_album:
      type: str
      sonos_recv: track_album

    track_album_art:
      type: str
      sonos_recv: track_album_art

    radio_station:
      type: str
      sonos_recv: radio_station

    radio_show:
      type: str
      sonos_recv: radio_show

    current_track:
      type: num
      sonos_recv: current_track

    number_of_tracks:
      type: num
      sonos_recv: number_of_tracks

    current_track_duration:
      type: str
      sonos_recv: current_track_duration

    current_transport_actions:
      type: str
      sonos_recv: current_transport_actions

    current_valid_play_modes:
      type: str
      sonos_recv: current_valid_play_modes

    stream_content:
      type: str
      sonos_recv: stream_content

    play_tunein:
      type: str
      sonos_send: play_tunein

      start_after:
        type: bool
        value: True
        sonos_attrib: start_after

    play_url:
      type: str
      sonos_send: play_url

      start_after:
        type: bool
        value: True
        sonos_attrib: start_after

    start_after:
        type: bool
        value: False
        sonos_attrib: start_after

    sonos_playlists:
      type: list
      sonos_recv: sonos_playlists

    load_sonos_playlist:
      type: str
      sonos_send: load_sonos_playlist
      enforce_updates: True

      start_after:
        type: bool
        value: False
        sonos_attrib: start_after

      start_track:
        type: num
        value: 0
        sonos_attrib: start_track

      clear_queue:
        type: bool
        value: False
        sonos_attrib: clear_queue

  play_tts:
    type: str
    sonos_send: play_tts
    enforce_updates: True

    tts_language:
      type: str
      value: de
      sonos_attrib: tts_language

    tts_volume:
      type: num
      value: -1
      sonos_attrib: tts_volume

    tts_fade_in:
      type: bool
      sonos_attrib: tts_fade_in

  play_snippet:
    type: str
    sonos_send: play_snippet
    enforce_updates: True

    snippet_volume:
      type: num
      value: 25
      sonos_attrib: snippet_volume

    snippet_fade_in:
      type: bool
      value: True
      sonos_attrib: snippet_fade_in

plugin_functions: NONE

logic_parameters: NONE